Dev private events
Wusinho/private-events pull request #3
Opened 2021-03-09 16:48 UTC by Wusinho

Private Events

2021-03-09 22:11 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Juan Lazo Benza** 
Good job with your first submission for this project :muscle:  :muscle:
It most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] Fix rubocop offenses
- [ ] Use Rspec + Capybara for the unit and integration tests

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png)

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png)

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png)

- [ ] User should be able to attend events
- [ ] the show page of an event should also show the list of attendants

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png)
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-03-16 22:57 UTC, enaburekhan requested changes
# Status: Changes required:full_moon:
**Hi team!
Great job so far. Thank you for implementing some of the changes requested by the last reviewer:clap::clap:.**

**major highlights**

- The UI is awesome and logged in user can create new event
- Navigation links are present at the top of the page.
- Event's index page displays past and upcoming events list.

However, we still need to make a few changes to get the project approved:muscle:.

**To improve**

**EventsController**

- [ ] `create` action

-  uses #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). You did implement this. But the Build method is missing. Pls add it.

- [x] `index` action

- lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). This is currently missing. Please add it.

- lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Also account for this.

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. As already highlighted in the PR below, Move all logics in view to a helper. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) on how to use a helper in rails. Also, see [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright.

- [ ] Remove commented-out code from events_controller.rb. and attendances_controller.rb. They make the codebase to be untidy and the codes difficult to read and understand. 

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy coding:blush:
Eric Enaburekhan

2021-03-16 22:57 UTC, enaburekhan commented on README.md
> +### How to use the aplication
Correct spelling error: it should be `application`

2021-03-16 22:57 UTC, enaburekhan commented on app/controllers/events_controller.rb
> +    @event = Event.new(event_params)
uses #build method on association, i.e. current_user.events.build(event_params).

2021-03-16 22:57 UTC, enaburekhan commented on app/controllers/events_controller.rb
> +  end
It should list the past and upcoming events. E,g 
def index
  @past_events = Event.previous_events
  @upcoming_events = Event.upcoming_events
end

2021-03-16 22:57 UTC, enaburekhan commented on app/views/events/_show.html.erb
> +        <% end %>
There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Kindly move them to a helper.

2021-03-16 22:57 UTC, enaburekhan commented on app/views/events/show.html.erb
> +<%= link_to 'Back', events_path , class: "btn btn-secondary mt-4" %>
Also, move this logic to a helper.

2021-03-16 22:57 UTC, enaburekhan commented on app/views/users/new.html.erb
> +    <% end %>
Also, move this logic to a helper.

2021-03-16 22:57 UTC, enaburekhan commented on app/views/users/sign_up.html.erb
> +    <% end %>
Also, move this to a helper

2021-03-16 22:57 UTC, enaburekhan commented on app/views/users/show.html.erb
> +    <% else %>
Also, move this logic to a helper.

2021-03-16 22:57 UTC, enaburekhan commented on app/views/users/show.html.erb
> +    <% end %>
Move this logic to a helper

2021-03-17 16:33 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Amazing work. You made most of the changes requested. Well done!
You, however, missed a requested change, there's still some logic in views. I left you a comment with a suggestion.
Make the change and submit it for another review.


### Martin Afani
#### Slack: whiz25

2021-03-17 16:33 UTC, whiz25 commented on app/views/users/show.html.erb
> +    <% end %>
- Move this logic to a helper

2021-03-17 19:25 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔✔**
Great implementation of the project👏👏
You can merge👌👌👍👍

Happy coding💻💻💻

2021-03-17 19:56 UTC, merged